### ISSUE TITLE
QuickFormTool displaced by Tabs

### ISSUE THREAD

**Issue by hansnolte** [mohammadyaghobi/Brackets-QuickFormTool#7]
Hi mohammadyaghobi,

with these Plugins, QuickFormTool will be overlapped.
It is no longer operable. 

Document Toolbar(with tabs)
Tabs - Custom Working
Brackets Working File Tab

Please, can you fix it.

**Comment by fernamp** [comment]
It's easy to fix it.
Just open your extensions folder and search for "m.yaghobi.quickformtool", the get into "ui" folder and open style.css.

Modify this:

<code>
.qftmainblock {
padding: 0;
margin: 0;
height: 0px;
overflow:visible;
position: relative;
background-color:#47484b;
top: 26px; /* ADD THIS */
}
</code>

If you need more top space just change the number of pixels (top: XXpx).

**Comment by hansnolte** [comment]
Hi fernamp,

many thanks for your help.
Works great.

Many greetings
Hans
